- name: Install System Packages 1 (build-essential, cmake, pkg-config)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", ]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, wget, libtool, libtool-bin, gettext, tree)
  become: true
  apt:
    name: [ "lua5.1", "unzip", "wget", "libtool", "libtool-bin", "gettext", "tree"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name: [ "compton", "curl", "htop", "golang", "lsof", "bspwm", "sxhkd", "ninja-build", "python3-pip",  "pavucontrol",  ]
  tags:
    - install
    - core
