- name: Install packages
  become: true
  apt:
    name: [ "alacritty", "tmux", "blueman", "vlc", "mpv", "wireshark", "fzf", "zathura", "gimp", "xclip", "xdo", "xdotool",  "tldr", "sxiv", "tipp10", "klavaro", "rsync", "artha", "kcolorchooser", "ripgrep" ]
  tags:
    - install
    - productivity
